# XXX FIXME currently no HA deployments, 1 controller only
- hosts: controllers
  roles:
    - neutron_devstack
    - neutron_functional_tests
  vars:
    localrc: neutron_controller_localrc

- hosts: computes
  roles:
    - neutron_devstack
  vars:
    localrc: neutron_compute_localrc
