# Configures vim/git/etc for pleasant user experience
- name: install system dependencies
  apt: name={{item}} state=latest
  with_items:
      - ack-grep
      - vim
  sudo: yes

- name: clone repo with nice vim config
  git: repo=https://github.com/fernflower/vim-quickstart.git dest="/home/{{user}}/.vim" update=no

- name: update submodules in vim bundles
  command: chdir="/home/{{user}}/.vim" git submodule update --init

- name: make symlinc for vimrc
  file: src="/home/{{user}}/.vim/vimrc" dest="/home/{{user}}/.vimrc" owner={{user}} state=link

- name: set proper git editor
  command: git config --global core.editor "vim"

- name: run BundleInstall
  command: vim +BundleInstall +qall

