- apt: update-cache=yes
  sudo: yes

- name: install system dependencies
  apt: name={{item}} state=latest
  with_items:
      - git
      - git-review
      - build-essential
      - python2.7
      - language-pack-ru
  sudo: yes

- include: basic_tweaks.yml

- name: checkout devstack repo
  git: repo=https://git.openstack.org/openstack-dev/devstack dest="{{project_dir}}/devstack" update=no

- name: checkout neutron_for_dummies (just in case)
  git: repo=https://github.com/fernflower/neutron_for_dummies.git dest="{{project_dir}}/neutron_for_dummies" update=no

- name: checkout neutron repo
  git: repo=https://github.com/openstack/neutron.git update=no dest={{project_dir}}/neutron

- name: copy py2 localrc to devstack dir
  template: src="{{localrc}}.j2" dest="{{project_dir}}/devstack/localrc"

- name: verify ADMIN_PASSWORD is set in localrc
  shell: grep "ADMIN_PASSWORD=" "{{project_dir}}/devstack/localrc"
  register: check_password_set
  always_run: True
  changed_when: False

- name: check for devstack screen session
  shell: screen -ls stack | awk '$0~/No Sockets found/{print "no session"}'
  register: screen_session_exists

- name: run stack.sh
  shell: bash "{{project_dir}}/devstack/stack.sh"
  when: screen_session_exists.stdout == "no session"
