- hosts: nodes
  tasks:
- name: switch to iptables firewall
  ini_file: dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
            section=securitygroup
            option=firewall_driver 
            value="neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver"
