- hosts: nodes
  tasks:
    - name: switch to ovs firewall
      ini_file: dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini
                section=securitygroup
                option=firewall_driver 
                value=openvswitch

# restart ovs agent on computes
- hosts: computes
  roles:
    - restart_compute

# XXX controller needs manual restart via pcs
