- hosts: master
  roles: 
    - kernel4_4
  vars:
    - project_dir: /root

# reboot all nodes so that they discover new kernel
- hosts: nodes
  tasks:
    - name: reboot node
      command: /sbin/reboot

    - name: wait for ssh to come up again
      local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
