- apt: update-cache=yes
  sudo: yes

- name: install system dependencies
  apt: name={{item}} state=latest
  with_items:
      - git
      - python-virtualenv
  sudo: yes

- name: checkout shaker repo
  git: repo=https://github.com/openstack/shaker.git dest="{{project_dir}}/shaker" update=no

- name: create virtualenv
  command: virtualenv "{{project_dir}}/.venv" -p python2.7

- name: install shaker
  pip: name=pyshaker virtualenv="{{project_dir}}/.venv"

- name: create source shaker script
  template: src=with_shaker_venv.j2 dest="{{project_dir}}/with_shaker_venv.sh"

- name: run shaker-image-builder
  command: /bin/bash "{{project_dir}}/with_shaker_venv.sh" shaker-image-builder
