- apt: update-cache=yes
  sudo: yes

- name: get linux-image-generic-lts-xenial
  apt: name={{item}} state=latest
  with_items:
    - linux-image-generic-lts-xenial
  sudo: yes

- name: reboot node
  command: /sbin/reboot
  sudo: yes

- name: wait for ssh to come up again
  local_action: wait_for host="{{inventory_hostname}}" search_regex=OpenSSH port=22 timeout=120
